Remote x11 forwarding
purdue-arc/rocket_league pull request #113
Opened 2022-03-27 18:56 UTC by jaketockerman

use --net=host on server and ssh -Y to pass x11 forwarding over ssh

2022-03-28 12:33 UTC, jrbaxter0 approved these changes
As long as you provided **detailed** instructions to members over Discord, this is fine with me. I have not reviewed the server functionality at all since that is not my domain. When this is merged, I expect there to be an @rocketleague announcement on #rl-general with the exact copy-paste command to rename the image.

2022-03-28 12:37 UTC, jrbaxter0 commented
But as a comment, if you use `--net host` when running on the server, only one person can be running ROS stuff at a time by default. It will use port 11311 and get upset that there is already something running. You can change the default port, which is something I do for training hundreds of simultaneous environments on the super computer. But that code is somewhat flakey.

Probably you want to bind only the port actually needed for display.

2022-03-28 12:39 UTC, jrbaxter0 commented
It also might be better to use this solution so that each user's docker images / containers are specific to themselves. Then you don't need to worry about people killing other's stuff, and doing this tagging stuff: https://forums.docker.com/t/share-docker-between-users/5728

2022-03-28 12:39 UTC, jrbaxter0 commented
But again, whatever solution you decide on for the server is fine as long as it doesn't break the repo.

2022-04-01 13:13 UTC, jrbaxter0 requested changes
My review is primarily concerned with "will this break the project?" as opposed to "will this work on the server?"

That being said, my two major issues are with the comments in made in `docker-run.sh`. All the other comments are just suggestions.

I also think we should update the Docker README and link to it in the main README like we do other sections.

2022-04-01 13:13 UTC, jrbaxter0 commented on docker/docker-run.sh
> +    -v $HOME/.Xauthority:/home/$USER/.Xauthority \
This is not portable to Mac. We already do this exact thing on line 19, but do it as read only, which I'd prefer unless if there is a need to be able to change it.

2022-04-03 19:05 UTC, hmccarty commented
Works for me

2022-04-04 12:37 UTC, jrbaxter0 approved these changes
Changes to `-build`, `-join`, `-run` look good to me. Will not mess up any existing workflows if containers are rebuilt when merged.

2022-04-04 12:55 UTC, merged